#!/usr/bin/env bash
# checking for command line arguments

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# assigning paramentals to variables

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

#disabbling strict host key checking

scp -o "strictHostKeyChecking=no" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"

# checking if the transfer was successful

if [ $? -eq 0 ]
then
	echo "FILE WAS TRANSFERED SUCCESSFULLY"
else
	echo "FILE TRANSFER FAILD"
fi
