#!/usr/bin/env bash
# Commands to install Nginx on a web server

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Allow HTTP traffic for Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a test HTML file
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply any changes
sudo service nginx reload

