#!/usr/bin/env bash

# Copy the current hosts file to a new file in the user's home directory
cp /etc/hosts ~/hosts.new

# Add a new entry for localhost with IP address 127.0.0.2 to the new hosts file
echo "127.0.0.2		localhost" > ~/hosts.new

# Append an entry for Facebook with IP address 8.8.8.8 to the new hosts file
echo "8.8.8.8		facebook.com" >> ~/hosts.new

# Overwrite the system's hosts file with the updated one
cp -f ~/hosts.new /etc/hosts
